### ISSUE TITLE
flutter 내부에 .tflite 파일로 된 모델이 필요한가?

### ISSUE THREAD

**Issue by Ryuchanghoon** [ProjectBARO/BARO-AI#5]
### 이유:

1. 실시간 좌표추출, 각도 계산 출력은 모델 내부 탑제 불가능.
2. 그래서 학습한 모델(.tflite)에 이 출력값을 다시 넣고 돌려야 함.
3. 실시간이면 차라리 모델 test 거치지 않고, 계산 결과값만 빠르게 넘기는게 어떤지.

### 결론: 

실시간이 목적이면 과정이 쓸데없이 복잡함으로, 이중 과정을 거치는 것 보다 한 과정으로 간소화 하는게 어떤지.

**Comment by YehyeokBang** [comment]
따로 디스코드를 통해 회의를 해보는 것이 더 좋을 것 같습니다.

**Comment by Ryuchanghoon** [comment]
해결 완료. 이슈 닫을게요~
