### ISSUE TITLE
Flask 활용 모델 api 화

### ISSUE THREAD

**Issue by Ryuchanghoon** [ProjectBARO/BARO-AI#6]
- [x] Flask로 Local 결과값 확인
- [x]  모델 도커 이미지 빌드
- [x] 도커 이미지 API화

**Comment by YehyeokBang** [comment]
FastAPI 말고 Flask를 통해 API화 시켰습니다. 같이 확인 후 수정하면 될 것 같아요.

**Comment by Ryuchanghoon** [comment]
Flask로 수정하도록 하겠습니다!

**Comment by YehyeokBang** [comment]
Good~
